services:
 grafana:
   image: grafana/grafana
   ports:
   - '3010:3000'
   environment:
     GF_RENDERING_SERVER_URL: http://renderer:8081/render
     GF_RENDERING_CALLBACK_URL: http://grafana:3000/
     GF_LOG_FILTERS: rendering:debug
   volumes:
     - grafana-storage:/var/lib/grafana
     - grafana-cfg:/etc/grafana/
     - grafana-log:/var/log/grafana
 renderer:
   image: grafana/grafana-image-renderer:3.5.0
   ports:
   - 8081
volumes:
 grafana-storage:
 grafana-log:
 grafana-cfg:
