version: '3'

services:
  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: no #unless-stopped | always | on-failure
    networks:
      - mariadb
    ports:
      - 7777:8080      


networks:
    mariadb:
        external: true    
